### Site Settings ###
title               : Vijay Raghavan
description         : >-
  Software Engineer and Aspiring Product Manager.
baseurl             : "/"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
#repository          : vijay-raghav/vijay-raghav.github.io    # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Vijay Raghavan
  image             : ../assets/images/profilepic.jpg
  behance           : vijayr9
# dribbble          : your_username
# email             : vijaysgr8@gmail.com
#  facebook          : your_username
  github            : vijay-raghav
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : vijayraghavans
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : anon108er
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  posts:
    output: true
    permalink: /posts/:title
#  elements:                                             # For Documentation Only
#    output: true                                        # For Documentation Only


### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"                                  # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false     

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
